### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by Timon147** [zspitz/ExpressionTreeVisualizer#102]
I have a stupid question, how do I use ExpressionTreeVisualizer? I am a newbie and don't know how to use Github.

**Comment by zspitz** [comment]
Not a stupid question. In short:

1. Go to the [Releases page](https://github.com/zspitz/ExpressionTreeVisualizer/releases).
2. Download the ZIP file appropriate to your version of Visual Studio (2019 or 2017).
3. Extract the contents to the [visualizers folder](https://docs.microsoft.com/en-us/visualstudio/debugger/how-to-install-a-visualizer?view=vs-2019). You can put the files in either:

    * `My Documents\` _VisualStudioVersion_ `\Visualizers`, for all instances of that VS version installed on your machine, or
    * _VisualStudioInstallPath_ `\Common7\Packages\Debugger\Visualizers`, for a specific instance of VS

4. When you hit a breakpoint and you hover over an expression in the editor pane, or in the Watch, Locals, or Autos pane, you should see a small magnifying glass with a dropdown. You should be able to choose "Expression Tree Visualizer" from the dropdown. See [here](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/expression-trees/debugging-expression-trees-in-visual-studio).

**Comment by Timon147** [comment]
Perfect, I got it now!
It‘s really a good Visualizer.
Thank you so much!
