### ISSUE TITLE
Can't load the assembly System.Runtime error

### ISSUE THREAD

**Issue by Enderlook** [zspitz/ExpressionTreeVisualizer#103]
**Describe the bug**  
Got the following error when trying to use the extension (translated from Spanish):
```
Can't load the custom visualizer.
Can't load the file or assembly 'System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. A program with wrong format has been tried to load.
```

**To Reproduce**  

1. Download release 1.6.80 ExpressionTreeVisualizer.2019.zip
2. Unzip content in `C:\Users\USERNAME\Documents\Visual Studio 2019\Visualizers`
3. Open Visual Studio 2019 Community v16.4.4
4. Execute as debug my code.
5. Press the magnifying glass icon.

**Expected behavior**  
See the expression tree visualizer window.

**Version info:**

- Visual Studio version: Visual Studio 2019 Community v16.4.4
- Visualizer location: `C:\Users\USERNAME\Documents\Visual Studio 2019\Visualizers`
- Version: 1.6.80

**Additional context**  

- The problem happen with any expression I try to debug.

- My project settings have the following group:
```
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>
```

**Comment by zspitz** [comment]
Thanks.

RE: unblocking, Windows has a security feature that some files that came from the Internet are blocked -- there are some limitations on their use. See the [Troubleshooting visualizer installation](https://github.com/zspitz/ExpressionTreeVisualizer/wiki/Troubleshooting-visualizer-installation) wiki page.

I will try to reproduce this, probably after the weekend.

**Comment by Enderlook** [comment]
Unblocking the files didn't fix the error in my PC.
However, placing an additional copy of the extension in `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Packages\Debugger\Visualizers` **did** fix it.
Thanks for link

**Comment by victor-pogor** [comment]
Same behavior, same solution.

**Comment by zspitz** [comment]
The workaround should no longer be needed.
