### ISSUE TITLE
Please consider of adding a link to released zip files in README

### ISSUE THREAD

**Issue by ljsnogard** [zspitz/ExpressionTreeVisualizer#104]
As I don't see a release link from the project home page.
And I got confused about what the term 'zip file' means.
Then I search issues and find 'How to use it', the 'stupid question'.
And finally 'oh there you are'.

So please consider of marking the '[ZIP file](https://github.com/zspitz/ExpressionTreeVisualizer/releases)' a link to release page in README, the installation part. 
For those who have never heard of the term `visualizer`, it will be helpful I think.

Thank you for your consideration.

**Comment by zspitz** [comment]
@ljsnogard Is [this](https://github.com/zspitz/ExpressionTreeVisualizer/blob/master/README.md#installation) better? If not, how can I make it more obvious?

**Comment by ljsnogard** [comment]
> 
> 
> @ljsnogard Is [this](https://github.com/zspitz/ExpressionTreeVisualizer/blob/master/README.md#installation) better? If not, how can I make it more obvious?

Very good for me!
Again thank you for your great jobs.
