### ISSUE TITLE
consider creating a REAL extension for VS instead of a crappy installer

### ISSUE THREAD

**Issue by d4e666** [zspitz/ExpressionTreeVisualizer#105]
**Version info:**

- Visual Studio version:
- Visualizer location: [VS install path, or Documents subfolder]
- Version: [GitHub release version or project commit]

Note that the visualizer location and version can be found at the bottom of the **Settings** popup (click the gear icon).

**Is your feature request related to a problem? Please describe.**  

**Screenshots**  
If applicable, add screenshots to help explain the problem you are trying to solve.

**Describe the solution you'd like**  

**Describe alternatives you've considered**  

**Additional context**

**Comment by zspitz** [comment]
Actually, there is no installer; consider editing the title. 😊

AFAIK VS extensions aren't designed for installing debugging visualizers; and writing an extension involves a lot of development overhead, which might turn out to be useless. A standard Wix installer might be a better solution, but they cannot be self-updated like other VS extensions.

Perhaps when I have some time to devote to this, I'll create an actual installer.

How is the current XCOPY installation a problem for you?

**Comment by zspitz** [comment]
@d4e666 This is being closed in favor of #106. If you have anything further to add, please add it there.
