### ISSUE TITLE
Could not load file or assembly 'System.Runtime, Version=4.2.0.0' or one of its dependencies

### ISSUE THREAD

**Issue by babula38** [zspitz/ExpressionTreeVisualizer#110]
![error](https://user-images.githubusercontent.com/4153708/82110231-27467080-975a-11ea-9adc-5ff10c66a8e0.jpg)

blow are some details which might help you.

- Visual studio version:- vs2019 community latest preview.
- Expression tree version:- took latest from the github release
- .Net Framework used:- .net core 3.1 with xunit project.

below is the expression.
```csharp
.Lambda #Lambda1<System.Func`3[MyExpression.lib.test.MyClass,MyExpression.lib.test.MyClass1,MyExpression.lib.test.MyClass]>(
    MyExpression.lib.test.MyClass $myClass,
    MyExpression.lib.test.MyClass1 $myclass1) {
    .Block() {
        .Block() {
            $myClass.MyProperty = $myclass1.MyProperty;
            $myClass.MyProperty = $myclass1.MyProperty
        };
        $myClass
    }
}
```

Do let me know if you some other information also.

**Comment by zspitz** [comment]
I'm not sure why this happens; but other people have reported it as well. (https://github.com/zspitz/ExpressionTreeVisualizer/issues/103).

I haven't been able to duplicate this.

You can workaround this by installing the visualizer to the Visual Studio install path, instead of the subfolder under Documents, as described [here](https://docs.microsoft.com/en-us/visualstudio/debugger/how-to-install-a-visualizer?view=vs-2019).

**Comment by babula38** [comment]
I have placed the dll inside Visual studio install path, i am getting the below error now.

```csharp
Unable to perform function evaluation on the process being debugged.

Additional information:- 
Evaluation timed out

at Microsoft.VisualStudio.DebuggerVisualizers.Impl.VisualizerObjectProvider.Create(IVisualizerObjectProviderInternal visualizerObjectProviderInternal)
at ClrCustomVisualizerVSHost.ClrCustomVisualizerVSHostHelper.DisplayValue(IntPtr hWnd, SuccessEvaluationResultProxy evaluationResult, Int32 selectedIndex, DkmApiVersion protocolVersion)
```

**Comment by zspitz** [comment]
Once you called `.Compile()` on the expression, you can open the visualizer on the original expression, not on the result of the compilation? That's rather strange.

Could you add a reference to https://www.nuget.org/packages/ExpressionTreeToString/ and call the ToString extension method on your expression?
```
// using ExpressionTreeToString;
Expression expr = ...
var tostring = expr.ToString("Object notation");
```

**Comment by zspitz** [comment]
I was able to reproduce with a .NET Core 3.1 project. I'm investigating further.

**Comment by zspitz** [comment]
A possibly relevant link: https://github.com/dotnet/standard/issues/481#issuecomment-429653699

**Comment by zspitz** [comment]
I've isolated this to the use of Costura on the debugger side; using Costura on the debuggee side doesn't cause a problem.

**Comment by zspitz** [comment]
@babula38 Could you try the latest release?

**Comment by babula38** [comment]
@zspitz thanks, it is working now, if I install it in visual studio installer directory.
