### ISSUE TITLE
Exception in use

### ISSUE THREAD

**Issue by stulzq** [zspitz/ExpressionTreeVisualizer#113]
**Version info:**

- Visual Studio version: Visual Studio 2019 16.6.0
- Visualizer location: `C:\Users\admin\Documents\Visual Studio 2019\Visualizers`
![image](https://user-images.githubusercontent.com/13200155/84486274-c44fe700-accf-11ea-8501-3947e04987c1.png)

- Version: 1.7.98

- Exception

![image](https://user-images.githubusercontent.com/13200155/84486412-f7927600-accf-11ea-990a-de404600344c.png)

Debug Project is  Console App .NET Core 3.1

**Comment by zspitz** [comment]
I've updated the release; it should work now.

**Comment by zspitz** [comment]
@stulzq Any news?

**Comment by zspitz** [comment]
CI has now been fixed. https://github.com/zspitz/ExpressionTreeVisualizer/blob/master/appveyor.yml#L42

**Comment by stulzq** [comment]
OK, I'll try and reply here

**Comment by stulzq** [comment]
It works. Thank you very much
