### ISSUE TITLE
I've installed it, but how can I use it?

### ISSUE THREAD

**Issue by zico209** [zspitz/ExpressionTreeVisualizer#118]
Will there be a magnifying glass to click on it? I don't have it.

**Comment by zspitz** [comment]
You have to have Visual Studio attached to the program, and you also need the program to be stopped, so you can examine variables and expressions. Once you've done that, you can hover over an `Expression` instance and you should see the magnifying glass.
![run-visualizer](https://user-images.githubusercontent.com/312166/100055149-13c44280-2e2c-11eb-816d-f5f03b9dd9e4.gif)

**Comment by zico209** [comment]
My practice is the same as you, at first it doesn't work, and then I send it to my friend to try, and he can run it. So I fixed my virtual studio .It works.牛逼

**Comment by zspitz** [comment]
Glad to hear it.
